// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoschxpwbgvuxdgewhse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvc2NoeHB3Ymd2dXhkZ2V3aHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODgyMjAsImV4cCI6MjA2OTQ2NDIyMH0.20-zP_D6UHZQu0_36VsyFsvWw9yhvczuy5ZZMKRLgMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});